#name of the workflow
name: docker application

on:
  push:
    branches:
      - "main"

#jobs

jobs:
  build-run-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository content
        uses: action/checkout@v3